language: 
  - node_js
sudo: false
node_js:
  - "0.12"
branches:
  only:
    - master
install:
    - npm install
    - npm install -g bower
    - bower install
script:
  - npm test
before_install:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
