var app = angular.module('demoApp', ['ng-emphasis']);

app.config(['ngEmphasisConfigProvider', function(ngEmphasisConfigProvider) {
    ngEmphasisConfigProvider.setCssClass('highlight');
}]);

app.controller('MainCtrl', function($scope) {
  
  var vm = this;
  
  vm.appName = 'ng-emphasis';
  vm.searchText = 'phil';
  vm.users = [{
      "id": 1,
      "first_name": "Chris",
      "last_name": "Matthews",
      "email": "cmatthews0@ocn.ne.jp",
      "gender": "Male",
      "ip_address": "38.15.206.68"
    }, {
      "id": 2,
      "first_name": "Keith",
      "last_name": "Ferguson",
      "email": "kferguson1@shop-pro.jp",
      "gender": "Male",
      "ip_address": "84.41.124.116"
    }, {
      "id": 3,
      "first_name": "Philip",
      "last_name": "Ford",
      "email": "pford2@yellowpages.com",
      "gender": "Male",
      "ip_address": "34.193.23.41"
    }, {
      "id": 4,
      "first_name": "Henry",
      "last_name": "Stanley",
      "email": "hstanley3@bbc.co.uk",
      "gender": "Male",
      "ip_address": "82.211.205.255"
    }, {
      "id": 5,
      "first_name": "Anna",
      "last_name": "Hayes",
      "email": "ahayes4@ycombinator.com",
      "gender": "Female",
      "ip_address": "99.11.17.116"
    }, {
      "id": 6,
      "first_name": "Barbara",
      "last_name": "Lane",
      "email": "blane5@stumbleupon.com",
      "gender": "Female",
      "ip_address": "152.203.161.214"
    }, {
      "id": 7,
      "first_name": "Frances",
      "last_name": "Schmidt",
      "email": "fschmidt6@live.com",
      "gender": "Female",
      "ip_address": "167.147.181.201"
    }, {
      "id": 8,
      "first_name": "Philip",
      "last_name": "Bowman",
      "email": "pbowman7@weebly.com",
      "gender": "Male",
      "ip_address": "36.162.246.20"
    }, {
      "id": 9,
      "first_name": "Robert",
      "last_name": "Fields",
      "email": "rfields8@bravesites.com",
      "gender": "Male",
      "ip_address": "24.91.76.110"
    }, {
      "id": 10,
      "first_name": "Jonathan",
      "last_name": "Stanley",
      "email": "jstanley9@storify.com",
      "gender": "Male",
      "ip_address": "153.66.210.98"
    }, {
      "id": 11,
      "first_name": "Andrea",
      "last_name": "Alexander",
      "email": "aalexandera@yahoo.com",
      "gender": "Female",
      "ip_address": "122.234.36.78"
    }, {
      "id": 12,
      "first_name": "Lois",
      "last_name": "Richards",
      "email": "lrichardsb@flavors.me",
      "gender": "Female",
      "ip_address": "197.137.7.123"
    }, {
      "id": 13,
      "first_name": "Margaret",
      "last_name": "Smith",
      "email": "msmithc@theatlantic.com",
      "gender": "Female",
      "ip_address": "165.106.224.119"
    }, {
      "id": 14,
      "first_name": "Brenda",
      "last_name": "Rivera",
      "email": "briverad@themeforest.net",
      "gender": "Female",
      "ip_address": "224.4.250.105"
    }, {
      "id": 15,
      "first_name": "Joan",
      "last_name": "Morrison",
      "email": "jmorrisone@hhs.gov",
      "gender": "Female",
      "ip_address": "188.168.190.239"
    }, {
      "id": 16,
      "first_name": "Daniel",
      "last_name": "Jackson",
      "email": "djacksonf@lulu.com",
      "gender": "Male",
      "ip_address": "7.212.208.37"
    }, {
      "id": 17,
      "first_name": "Willie",
      "last_name": "Harris",
      "email": "wharrisg@tiny.cc",
      "gender": "Male",
      "ip_address": "250.100.144.152"
    }, {
      "id": 18,
      "first_name": "Nicholas",
      "last_name": "Knight",
      "email": "nknighth@washington.edu",
      "gender": "Male",
      "ip_address": "188.136.105.114"
    }, {
      "id": 19,
      "first_name": "Larry",
      "last_name": "Miller",
      "email": "lmilleri@comcast.net",
      "gender": "Male",
      "ip_address": "68.227.52.170"
    }, {
      "id": 20,
      "first_name": "Willie",
      "last_name": "Watkins",
      "email": "wwatkinsj@irs.gov",
      "gender": "Male",
      "ip_address": "99.95.178.145"
    }, {
      "id": 21,
      "first_name": "Michelle",
      "last_name": "George",
      "email": "mgeorgek@sina.com.cn",
      "gender": "Female",
      "ip_address": "98.254.81.108"
    }, {
      "id": 22,
      "first_name": "Jose",
      "last_name": "Murray",
      "email": "jmurrayl@goo.gl",
      "gender": "Male",
      "ip_address": "250.194.126.231"
    }, {
      "id": 23,
      "first_name": "Irene",
      "last_name": "Barnes",
      "email": "ibarnesm@multiply.com",
      "gender": "Female",
      "ip_address": "96.241.230.79"
    }, {
      "id": 24,
      "first_name": "Eric",
      "last_name": "Watson",
      "email": "ewatsonn@answers.com",
      "gender": "Male",
      "ip_address": "102.50.181.13"
    }, {
      "id": 25,
      "first_name": "Carol",
      "last_name": "Thompson",
      "email": "cthompsono@vinaora.com",
      "gender": "Female",
      "ip_address": "103.39.144.240"
    }, {
      "id": 26,
      "first_name": "Phillip",
      "last_name": "Evans",
      "email": "pevansp@macromedia.com",
      "gender": "Male",
      "ip_address": "22.49.77.50"
    }, {
      "id": 27,
      "first_name": "Keith",
      "last_name": "Ortiz",
      "email": "kortizq@w3.org",
      "gender": "Male",
      "ip_address": "181.87.16.129"
    }, {
      "id": 28,
      "first_name": "Nicole",
      "last_name": "Ramirez",
      "email": "nramirezr@fema.gov",
      "gender": "Female",
      "ip_address": "58.219.204.158"
    }, {
      "id": 29,
      "first_name": "Daniel",
      "last_name": "Boyd",
      "email": "dboyds@elpais.com",
      "gender": "Male",
      "ip_address": "202.56.62.155"
    }, {
      "id": 30,
      "first_name": "Joe",
      "last_name": "Phillips",
      "email": "jphillipst@bizjournals.com",
      "gender": "Male",
      "ip_address": "23.188.38.231"
    }, {
      "id": 31,
      "first_name": "Kathy",
      "last_name": "Hunter",
      "email": "khunteru@photobucket.com",
      "gender": "Female",
      "ip_address": "18.217.230.91"
    }, {
      "id": 32,
      "first_name": "Carl",
      "last_name": "Johnson",
      "email": "cjohnsonv@cdbaby.com",
      "gender": "Male",
      "ip_address": "97.37.2.86"
    }, {
      "id": 33,
      "first_name": "Wayne",
      "last_name": "Stephens",
      "email": "wstephensw@upenn.edu",
      "gender": "Male",
      "ip_address": "98.31.62.123"
    }, {
      "id": 34,
      "first_name": "Arthur",
      "last_name": "Cunningham",
      "email": "acunninghamx@wisc.edu",
      "gender": "Male",
      "ip_address": "255.19.126.121"
    }, {
      "id": 35,
      "first_name": "Eugene",
      "last_name": "Smith",
      "email": "esmithy@time.com",
      "gender": "Male",
      "ip_address": "88.190.114.28"
    }, {
      "id": 36,
      "first_name": "Joyce",
      "last_name": "Bishop",
      "email": "jbishopz@eventbrite.com",
      "gender": "Female",
      "ip_address": "214.160.245.231"
    }, {
      "id": 37,
      "first_name": "Ann",
      "last_name": "Andrews",
      "email": "aandrews10@prweb.com",
      "gender": "Female",
      "ip_address": "198.77.42.209"
    }, {
      "id": 38,
      "first_name": "Steve",
      "last_name": "Kelly",
      "email": "skelly11@mail.ru",
      "gender": "Male",
      "ip_address": "75.50.154.84"
    }, {
      "id": 39,
      "first_name": "Norma",
      "last_name": "Perry",
      "email": "nperry12@liveinternet.ru",
      "gender": "Female",
      "ip_address": "24.161.40.252"
    }, {
      "id": 40,
      "first_name": "Willie",
      "last_name": "Morales",
      "email": "wmorales13@samsung.com",
      "gender": "Male",
      "ip_address": "171.139.87.151"
    }, {
      "id": 41,
      "first_name": "Evelyn",
      "last_name": "Henry",
      "email": "ehenry14@dailymotion.com",
      "gender": "Female",
      "ip_address": "9.183.75.246"
    }, {
      "id": 42,
      "first_name": "Charles",
      "last_name": "Perkins",
      "email": "cperkins15@ucla.edu",
      "gender": "Male",
      "ip_address": "47.157.164.93"
    }, {
      "id": 43,
      "first_name": "Judith",
      "last_name": "Webb",
      "email": "jwebb16@marriott.com",
      "gender": "Female",
      "ip_address": "156.218.119.136"
    }, {
      "id": 44,
      "first_name": "Frances",
      "last_name": "Torres",
      "email": "ftorres17@fda.gov",
      "gender": "Female",
      "ip_address": "160.213.206.123"
    }, {
      "id": 45,
      "first_name": "Laura",
      "last_name": "Gonzales",
      "email": "lgonzales18@163.com",
      "gender": "Female",
      "ip_address": "215.220.250.118"
    }, {
      "id": 46,
      "first_name": "Joseph",
      "last_name": "Greene",
      "email": "jgreene19@multiply.com",
      "gender": "Male",
      "ip_address": "139.183.31.205"
    }, {
      "id": 47,
      "first_name": "Larry",
      "last_name": "Morris",
      "email": "lmorris1a@opera.com",
      "gender": "Male",
      "ip_address": "61.248.224.89"
    }, {
      "id": 48,
      "first_name": "Julia",
      "last_name": "Anderson",
      "email": "janderson1b@cnbc.com",
      "gender": "Female",
      "ip_address": "127.194.55.238"
    }, {
      "id": 49,
      "first_name": "Julie",
      "last_name": "Ellis",
      "email": "jellis1c@pagesperso-orange.fr",
      "gender": "Female",
      "ip_address": "43.190.220.156"
    }, {
      "id": 50,
      "first_name": "Bonnie",
      "last_name": "Romero",
      "email": "bromero1d@ocn.ne.jp",
      "gender": "Female",
      "ip_address": "98.244.117.217"
    }, {
      "id": 51,
      "first_name": "Teresa",
      "last_name": "Wilson",
      "email": "twilson1e@uol.com.br",
      "gender": "Female",
      "ip_address": "34.46.122.161"
    }, {
      "id": 52,
      "first_name": "Benjamin",
      "last_name": "Matthews",
      "email": "bmatthews1f@businessinsider.com",
      "gender": "Male",
      "ip_address": "38.92.96.121"
    }, {
      "id": 53,
      "first_name": "Janice",
      "last_name": "Garrett",
      "email": "jgarrett1g@bigcartel.com",
      "gender": "Female",
      "ip_address": "136.43.155.85"
    }, {
      "id": 54,
      "first_name": "Shirley",
      "last_name": "Green",
      "email": "sgreen1h@adobe.com",
      "gender": "Female",
      "ip_address": "164.242.210.180"
    }, {
      "id": 55,
      "first_name": "Jack",
      "last_name": "Wood",
      "email": "jwood1i@de.vu",
      "gender": "Male",
      "ip_address": "135.253.61.201"
    }, {
      "id": 56,
      "first_name": "Kathy",
      "last_name": "Evans",
      "email": "kevans1j@buzzfeed.com",
      "gender": "Female",
      "ip_address": "110.165.219.71"
    }, {
      "id": 57,
      "first_name": "Sarah",
      "last_name": "Mason",
      "email": "smason1k@example.com",
      "gender": "Female",
      "ip_address": "79.207.16.192"
    }, {
      "id": 58,
      "first_name": "Alan",
      "last_name": "Simpson",
      "email": "asimpson1l@google.com.hk",
      "gender": "Male",
      "ip_address": "231.51.90.173"
    }, {
      "id": 59,
      "first_name": "Christina",
      "last_name": "Weaver",
      "email": "cweaver1m@umich.edu",
      "gender": "Female",
      "ip_address": "145.234.186.78"
    }, {
      "id": 60,
      "first_name": "Brandon",
      "last_name": "Russell",
      "email": "brussell1n@census.gov",
      "gender": "Male",
      "ip_address": "233.174.12.114"
    }, {
      "id": 61,
      "first_name": "Todd",
      "last_name": "Clark",
      "email": "tclark1o@reverbnation.com",
      "gender": "Male",
      "ip_address": "41.194.137.84"
    }, {
      "id": 62,
      "first_name": "Willie",
      "last_name": "Little",
      "email": "wlittle1p@aol.com",
      "gender": "Male",
      "ip_address": "75.223.15.223"
    }, {
      "id": 63,
      "first_name": "Heather",
      "last_name": "Diaz",
      "email": "hdiaz1q@wikipedia.org",
      "gender": "Female",
      "ip_address": "183.127.129.239"
    }, {
      "id": 64,
      "first_name": "Tina",
      "last_name": "Gutierrez",
      "email": "tgutierrez1r@storify.com",
      "gender": "Female",
      "ip_address": "153.199.16.45"
    }, {
      "id": 65,
      "first_name": "Jacqueline",
      "last_name": "Medina",
      "email": "jmedina1s@joomla.org",
      "gender": "Female",
      "ip_address": "175.247.159.152"
    }, {
      "id": 66,
      "first_name": "Laura",
      "last_name": "Peters",
      "email": "lpeters1t@xing.com",
      "gender": "Female",
      "ip_address": "219.80.96.46"
    }, {
      "id": 67,
      "first_name": "William",
      "last_name": "Frazier",
      "email": "wfrazier1u@bbc.co.uk",
      "gender": "Male",
      "ip_address": "111.143.220.82"
    }, {
      "id": 68,
      "first_name": "Roy",
      "last_name": "Welch",
      "email": "rwelch1v@freewebs.com",
      "gender": "Male",
      "ip_address": "152.115.125.240"
    }, {
      "id": 69,
      "first_name": "Clarence",
      "last_name": "Ray",
      "email": "cray1w@blogtalkradio.com",
      "gender": "Male",
      "ip_address": "127.36.81.53"
    }, {
      "id": 70,
      "first_name": "Helen",
      "last_name": "Rice",
      "email": "hrice1x@infoseek.co.jp",
      "gender": "Female",
      "ip_address": "172.122.124.135"
    }, {
      "id": 71,
      "first_name": "Fred",
      "last_name": "Gonzalez",
      "email": "fgonzalez1y@theguardian.com",
      "gender": "Male",
      "ip_address": "111.185.71.121"
    }, {
      "id": 72,
      "first_name": "Rebecca",
      "last_name": "Armstrong",
      "email": "rarmstrong1z@google.com.au",
      "gender": "Female",
      "ip_address": "242.109.77.2"
    }, {
      "id": 73,
      "first_name": "Carl",
      "last_name": "Williams",
      "email": "cwilliams20@msn.com",
      "gender": "Male",
      "ip_address": "235.102.18.250"
    }, {
      "id": 74,
      "first_name": "David",
      "last_name": "Carr",
      "email": "dcarr21@list-manage.com",
      "gender": "Male",
      "ip_address": "252.136.176.62"
    }, {
      "id": 75,
      "first_name": "Margaret",
      "last_name": "Boyd",
      "email": "mboyd22@bizjournals.com",
      "gender": "Female",
      "ip_address": "129.113.245.172"
    }, {
      "id": 76,
      "first_name": "Douglas",
      "last_name": "Hicks",
      "email": "dhicks23@cnet.com",
      "gender": "Male",
      "ip_address": "125.58.86.230"
    }, {
      "id": 77,
      "first_name": "Linda",
      "last_name": "Perry",
      "email": "lperry24@quantcast.com",
      "gender": "Female",
      "ip_address": "134.236.202.11"
    }, {
      "id": 78,
      "first_name": "Christopher",
      "last_name": "Nelson",
      "email": "cnelson25@hubpages.com",
      "gender": "Male",
      "ip_address": "123.213.176.215"
    }, {
      "id": 79,
      "first_name": "Joan",
      "last_name": "Burton",
      "email": "jburton26@sciencedirect.com",
      "gender": "Female",
      "ip_address": "242.151.180.140"
    }, {
      "id": 80,
      "first_name": "Martha",
      "last_name": "Stewart",
      "email": "mstewart27@arizona.edu",
      "gender": "Female",
      "ip_address": "196.205.40.22"
    }, {
      "id": 81,
      "first_name": "David",
      "last_name": "Hudson",
      "email": "dhudson28@cbc.ca",
      "gender": "Male",
      "ip_address": "111.46.117.18"
    }, {
      "id": 82,
      "first_name": "Helen",
      "last_name": "Clark",
      "email": "hclark29@cafepress.com",
      "gender": "Female",
      "ip_address": "120.7.113.198"
    }, {
      "id": 83,
      "first_name": "Charles",
      "last_name": "Stevens",
      "email": "cstevens2a@hubpages.com",
      "gender": "Male",
      "ip_address": "164.68.170.140"
    }, {
      "id": 84,
      "first_name": "Lisa",
      "last_name": "Jones",
      "email": "ljones2b@apple.com",
      "gender": "Female",
      "ip_address": "87.189.133.142"
    }, {
      "id": 85,
      "first_name": "Laura",
      "last_name": "Harrison",
      "email": "lharrison2c@acquirethisname.com",
      "gender": "Female",
      "ip_address": "233.238.63.135"
    }, {
      "id": 86,
      "first_name": "Jack",
      "last_name": "Hill",
      "email": "jhill2d@mit.edu",
      "gender": "Male",
      "ip_address": "172.161.247.18"
    }, {
      "id": 87,
      "first_name": "Brenda",
      "last_name": "Gordon",
      "email": "bgordon2e@linkedin.com",
      "gender": "Female",
      "ip_address": "26.234.22.14"
    }, {
      "id": 88,
      "first_name": "Alice",
      "last_name": "Russell",
      "email": "arussell2f@uol.com.br",
      "gender": "Female",
      "ip_address": "98.243.243.78"
    }, {
      "id": 89,
      "first_name": "Linda",
      "last_name": "Martin",
      "email": "lmartin2g@nyu.edu",
      "gender": "Female",
      "ip_address": "171.87.167.214"
    }, {
      "id": 90,
      "first_name": "Christopher",
      "last_name": "Gilbert",
      "email": "cgilbert2h@yellowbook.com",
      "gender": "Male",
      "ip_address": "69.117.135.118"
    }, {
      "id": 91,
      "first_name": "William",
      "last_name": "Hayes",
      "email": "whayes2i@china.com.cn",
      "gender": "Male",
      "ip_address": "31.35.137.252"
    }, {
      "id": 92,
      "first_name": "Raymond",
      "last_name": "Henderson",
      "email": "rhenderson2j@is.gd",
      "gender": "Male",
      "ip_address": "155.13.52.109"
    }, {
      "id": 93,
      "first_name": "Joshua",
      "last_name": "Lewis",
      "email": "jlewis2k@techcrunch.com",
      "gender": "Male",
      "ip_address": "22.59.249.145"
    }, {
      "id": 94,
      "first_name": "Chris",
      "last_name": "Mendoza",
      "email": "cmendoza2l@imdb.com",
      "gender": "Male",
      "ip_address": "8.208.112.149"
    }, {
      "id": 95,
      "first_name": "Thomas",
      "last_name": "Stone",
      "email": "tstone2m@nifty.com",
      "gender": "Male",
      "ip_address": "154.134.5.211"
    }, {
      "id": 96,
      "first_name": "Carol",
      "last_name": "Hanson",
      "email": "chanson2n@nymag.com",
      "gender": "Female",
      "ip_address": "201.132.57.255"
    }, {
      "id": 97,
      "first_name": "Gregory",
      "last_name": "Torres",
      "email": "gtorres2o@wiley.com",
      "gender": "Male",
      "ip_address": "228.80.46.183"
    }, {
      "id": 98,
      "first_name": "Deborah",
      "last_name": "Richardson",
      "email": "drichardson2p@sohu.com",
      "gender": "Female",
      "ip_address": "9.16.213.79"
    }, {
      "id": 99,
      "first_name": "Lawrence",
      "last_name": "Turner",
      "email": "lturner2q@sakura.ne.jp",
      "gender": "Male",
      "ip_address": "189.126.219.5"
    }, {
      "id": 100,
      "first_name": "Jacqueline",
      "last_name": "Hart",
      "email": "jhart2r@addtoany.com",
      "gender": "Female",
      "ip_address": "148.1.46.43"
    }];
  
});